/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlantaRouteImport } from './routes/atlanta'
import { Route as KnoxvilleRouteImport } from './routes/knoxville'
import { Route as NashvilleRouteImport } from './routes/nashville'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlantaRoute = AtlantaRouteImport.update({
  id: '/atlanta',
  path: '/atlanta',
  getParentRoute: () => rootRouteImport,
} as any)
const KnoxvilleRoute = KnoxvilleRouteImport.update({
  id: '/knoxville',
  path: '/knoxville',
  getParentRoute: () => rootRouteImport,
} as any)
const NashvilleRoute = NashvilleRouteImport.update({
  id: '/nashville',
  path: '/nashville',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlanta': typeof AtlantaRoute
  '/knoxville': typeof KnoxvilleRoute
  '/nashville': typeof NashvilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlanta': typeof AtlantaRoute
  '/knoxville': typeof KnoxvilleRoute
  '/nashville': typeof NashvilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlanta': typeof AtlantaRoute
  '/knoxville': typeof KnoxvilleRoute
  '/nashville': typeof NashvilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlanta' | '/knoxville' | '/nashville'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlanta' | '/knoxville' | '/nashville'
  id: '__root__' | '/' | '/atlanta' | '/knoxville' | '/nashville'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlantaRoute: typeof AtlantaRoute
  KnoxvilleRoute: typeof KnoxvilleRoute
  NashvilleRoute: typeof NashvilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlanta': {
      id: '/atlanta'
      path: '/atlanta'
      fullPath: '/atlanta'
      preLoaderRoute: typeof AtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knoxville': {
      id: '/knoxville'
      path: '/knoxville'
      fullPath: '/knoxville'
      preLoaderRoute: typeof KnoxvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nashville': {
      id: '/nashville'
      path: '/nashville'
      fullPath: '/nashville'
      preLoaderRoute: typeof NashvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlantaRoute: AtlantaRoute,
  KnoxvilleRoute: KnoxvilleRoute,
  NashvilleRoute: NashvilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
