/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AshevilleRouteImport } from './routes/asheville'
import { Route as AtlantaRouteImport } from './routes/atlanta'
import { Route as ChattanoogaRouteImport } from './routes/chattanooga'
import { Route as CincinnatiRouteImport } from './routes/cincinnati'
import { Route as KnoxvilleRouteImport } from './routes/knoxville'
import { Route as LexingtonRouteImport } from './routes/lexington'
import { Route as LouisvilleRouteImport } from './routes/louisville'
import { Route as NashvilleRouteImport } from './routes/nashville'
import { Route as OrlandoRouteImport } from './routes/orlando'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AshevilleRoute = AshevilleRouteImport.update({
  id: '/asheville',
  path: '/asheville',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlantaRoute = AtlantaRouteImport.update({
  id: '/atlanta',
  path: '/atlanta',
  getParentRoute: () => rootRouteImport,
} as any)
const ChattanoogaRoute = ChattanoogaRouteImport.update({
  id: '/chattanooga',
  path: '/chattanooga',
  getParentRoute: () => rootRouteImport,
} as any)
const CincinnatiRoute = CincinnatiRouteImport.update({
  id: '/cincinnati',
  path: '/cincinnati',
  getParentRoute: () => rootRouteImport,
} as any)
const KnoxvilleRoute = KnoxvilleRouteImport.update({
  id: '/knoxville',
  path: '/knoxville',
  getParentRoute: () => rootRouteImport,
} as any)
const LexingtonRoute = LexingtonRouteImport.update({
  id: '/lexington',
  path: '/lexington',
  getParentRoute: () => rootRouteImport,
} as any)
const LouisvilleRoute = LouisvilleRouteImport.update({
  id: '/louisville',
  path: '/louisville',
  getParentRoute: () => rootRouteImport,
} as any)
const NashvilleRoute = NashvilleRouteImport.update({
  id: '/nashville',
  path: '/nashville',
  getParentRoute: () => rootRouteImport,
} as any)
const OrlandoRoute = OrlandoRouteImport.update({
  id: '/orlando',
  path: '/orlando',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asheville': typeof AshevilleRoute
  '/atlanta': typeof AtlantaRoute
  '/chattanooga': typeof ChattanoogaRoute
  '/cincinnati': typeof CincinnatiRoute
  '/knoxville': typeof KnoxvilleRoute
  '/lexington': typeof LexingtonRoute
  '/louisville': typeof LouisvilleRoute
  '/nashville': typeof NashvilleRoute
  '/orlando': typeof OrlandoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asheville': typeof AshevilleRoute
  '/atlanta': typeof AtlantaRoute
  '/chattanooga': typeof ChattanoogaRoute
  '/cincinnati': typeof CincinnatiRoute
  '/knoxville': typeof KnoxvilleRoute
  '/lexington': typeof LexingtonRoute
  '/louisville': typeof LouisvilleRoute
  '/nashville': typeof NashvilleRoute
  '/orlando': typeof OrlandoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asheville': typeof AshevilleRoute
  '/atlanta': typeof AtlantaRoute
  '/chattanooga': typeof ChattanoogaRoute
  '/cincinnati': typeof CincinnatiRoute
  '/knoxville': typeof KnoxvilleRoute
  '/lexington': typeof LexingtonRoute
  '/louisville': typeof LouisvilleRoute
  '/nashville': typeof NashvilleRoute
  '/orlando': typeof OrlandoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asheville'
    | '/atlanta'
    | '/chattanooga'
    | '/cincinnati'
    | '/knoxville'
    | '/lexington'
    | '/louisville'
    | '/nashville'
    | '/orlando'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asheville'
    | '/atlanta'
    | '/chattanooga'
    | '/cincinnati'
    | '/knoxville'
    | '/lexington'
    | '/louisville'
    | '/nashville'
    | '/orlando'
  id:
    | '__root__'
    | '/'
    | '/asheville'
    | '/atlanta'
    | '/chattanooga'
    | '/cincinnati'
    | '/knoxville'
    | '/lexington'
    | '/louisville'
    | '/nashville'
    | '/orlando'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AshevilleRoute: typeof AshevilleRoute
  AtlantaRoute: typeof AtlantaRoute
  ChattanoogaRoute: typeof ChattanoogaRoute
  CincinnatiRoute: typeof CincinnatiRoute
  KnoxvilleRoute: typeof KnoxvilleRoute
  LexingtonRoute: typeof LexingtonRoute
  LouisvilleRoute: typeof LouisvilleRoute
  NashvilleRoute: typeof NashvilleRoute
  OrlandoRoute: typeof OrlandoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asheville': {
      id: '/asheville'
      path: '/asheville'
      fullPath: '/asheville'
      preLoaderRoute: typeof AshevilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlanta': {
      id: '/atlanta'
      path: '/atlanta'
      fullPath: '/atlanta'
      preLoaderRoute: typeof AtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chattanooga': {
      id: '/chattanooga'
      path: '/chattanooga'
      fullPath: '/chattanooga'
      preLoaderRoute: typeof ChattanoogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cincinnati': {
      id: '/cincinnati'
      path: '/cincinnati'
      fullPath: '/cincinnati'
      preLoaderRoute: typeof CincinnatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knoxville': {
      id: '/knoxville'
      path: '/knoxville'
      fullPath: '/knoxville'
      preLoaderRoute: typeof KnoxvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexington': {
      id: '/lexington'
      path: '/lexington'
      fullPath: '/lexington'
      preLoaderRoute: typeof LexingtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louisville': {
      id: '/louisville'
      path: '/louisville'
      fullPath: '/louisville'
      preLoaderRoute: typeof LouisvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nashville': {
      id: '/nashville'
      path: '/nashville'
      fullPath: '/nashville'
      preLoaderRoute: typeof NashvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orlando': {
      id: '/orlando'
      path: '/orlando'
      fullPath: '/orlando'
      preLoaderRoute: typeof OrlandoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AshevilleRoute: AshevilleRoute,
  AtlantaRoute: AtlantaRoute,
  ChattanoogaRoute: ChattanoogaRoute,
  CincinnatiRoute: CincinnatiRoute,
  KnoxvilleRoute: KnoxvilleRoute,
  LexingtonRoute: LexingtonRoute,
  LouisvilleRoute: LouisvilleRoute,
  NashvilleRoute: NashvilleRoute,
  OrlandoRoute: OrlandoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
